import torch

# After padding, the dimensions of the event data are [x, y, t, p, valid],
# the "valid" indicates if this event is generated by padding
def pad_events(events, max_length):
    padded_events = torch.zeros((max_length, 5), dtype=events.dtype)
    padded_events[:len(events), :4] = events
    padded_events[:len(events), 4] = 1
    return padded_events